[prompt]
symbol = ">"
segments = ["user", "path", "exit_code", "time"]

[palette]
user_fg = "#ffffff"
user_bg = "#ed2947"

path_fg = "#eceff1"
path_bg_1 = "#1565c0"
path_bg_2 = "#00695c"
path_bg_3 = "#827717"
path_bg_4 = "#0d47a1"
path_bg_5 = "#2e7d32"
path_bg_6 = "#8d6e00"

exit_code_fg = "#ffcdd2"
exit_code_bg = "#b71c1c"

time_fg = "#b2dfdb"
time_bg = "#004d40"

symbol_fg = "#80cbc4"
