[prompt]
symbol = "‚ùØ"
segments = ["user", "path", "exit_code", "time"]

[palette]
user_fg = "#8ab4ff"
user_bg = "#112a68"

path_fg = "#ffdca8"
path_bg_1 = "#1f4725"
path_bg_2 = "#5a3a05"
path_bg_3 = "#3d2b0b"
path_bg_4 = "#4f1d1f"
path_bg_5 = "#4a1637"
path_bg_6 = "#3f1b62"

exit_code_fg = "#ffb3b3"
exit_code_bg = "#4a0000"

time_fg = "#ff82f9"
time_bg = "#2d124d"

symbol_fg = "#4c5f9e"
